language: ruby
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - npm install -g bower
  - bower install

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c5e0daae1aef95763ea2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
